[project]
name = "nuts"
dynamic= ["version"]
description = "Nats microservices framework"
authors = [
  { name = "Mike Oz", email = "kozloffsky@hotmail.com"}
]
readme = "README.md"
requires-python=">=3.10"
dependencies = [
  "nats-py",
  "rich"
]

[tool.hatch.version]
path = "nuts/__about__.py"

[tool.hatch.metadata]
allow-direct-references = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.hatch.build.targets.wheel]
pachages = ["nuts"]


[tool.hatch.envs.default.scripts]
server = "python example/service.py"
test = "pytest --cov=nuts --cov-report=term-missing {args}"

[tool.hatch.envs.default]
dev-mode = true
skip-install = false 
dependencies = [
  "pytest",
  "pytest-asyncio",
  "pytest-cov"
]


[tool.pytest.ini_options]
addopts = "--capture=sys"
asyncio_default_fixture_loop_scope = "function"

[tool.coverage.run]
branch = true
omit = [
  "nuts/actor.py"
]

[tool.coverage.report]
show_missing = true
